name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd node-server
          npm install

      - name: Set up .env file
        run: |
          cd node-server
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env

      - name: Run tests
        run: |
          cd node-server
          npm test
